# Generated by Django 2.2.10 on 2022-08-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airpods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airpods_model', models.CharField(blank=True, choices=[('Airpods Pro', 'Airpods Pro'), ('Airpods 2', 'Airpods 2'), ('Airpods', 'Airpods')], default=0, max_length=30, null=True)),
                ('charging_case', models.CharField(blank=True, choices=[('Wireless charging case', 'Wireless charging case'), ('Wired charging case', 'Wired charging case'), ('Don’t have idea', 'Don’t have idea')], default=0, max_length=30, null=True)),
                ('airpods_condition', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Broken', 'Broken'), ('Fair', 'Fair'), ('Good', 'Good'), ('Flawless', 'Flawless')], default=0, max_length=30, null=True)),
                ('offer', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('iPhone', 'iPhone'), ('iPad', 'iPad'), ('iPod', 'iPod'), ('Macbook', 'Macbook'), ('iWatch', 'iWatch'), ('Apple Tv', 'Apple Tv'), ('Android Phones', 'Android Phones'), ('Air Pods', 'Air Pods'), ('PC Laptop', 'PC Laptop'), ('Other', 'Other')], default=0, max_length=30)),
                ('info', models.CharField(blank=True, max_length=300, null=True)),
                ('imagePath', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GooglePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_model', models.CharField(choices=[('Pixel 4 XL', 'Pixel 4 XL'), ('Pixel 4', 'Pixel 4'), ('Pixel 3 XL', 'Pixel 3 XL'), ('Pixel 3a XL', 'Pixel 3a XL'), ('Pixel 3a', 'Pixel 3a'), ('Pixel 3', 'Pixel 3'), ('Pixel 2 XL', 'Pixel 2 XL'), ('Pixel 2', 'Pixel 2')], default=0, max_length=30)),
                ('google_capacity', models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True)),
                ('google_carrier', models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30, null=True)),
                ('google_condition', models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30, null=True)),
                ('google_functional', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('google_powercord', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('google_box', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('google_headset', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('offer', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ipad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipad_model', models.CharField(choices=[('iPadPro', 'iPad Pro'), ('ipadAir', 'iPad Air'), ('iPadMini', 'iPad mini'), ('iPad', 'iPad')], default=0, max_length=30)),
                ('ipad_generation', models.CharField(choices=[('1st Gen', '1st Gen'), ('2nd Gen', '2nd Gen'), ('3rd Gen', '3rd Gen'), ('4th Gen', '4th Gen'), ('5th Gen', '5th Gen'), ('6th Gen', '6th Gen'), ('7th Gen', '7th Gen')], default=0, max_length=30)),
                ('ipad_capacity', models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30)),
                ('ipad_carrier', models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30)),
                ('ipad_screensize', models.CharField(blank=True, choices=[('9.7"', '9.7"'), ('10.2"', '10.2"'), ('10.5"', '10.5"'), ('11"', '11"'), ('12.9"', '12.9"'), ('not known', 'Don’t have idea')], default=None, max_length=30, null=True)),
                ('ipad_condition', models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30)),
                ('offer', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone_model', models.CharField(choices=[('IPhone 11 Pro Max', 'IPhone 11 Pro Max'), ('Iphone 11 Pro', 'Iphone 11 Pro'), ('Iphone 11', 'Iphone 11'), ('Iphone XS Max', 'Iphone XS Max'), ('Iphone XS', 'Iphone XS'), ('Iphone XR', 'Iphone XR'), ('Iphone X', 'Iphone X'), ('Iphone 8 Plus', 'Iphone 8 Plus'), ('Iphone 8', 'Iphone 8'), ('Iphone 7 Plus', 'Iphone 7 Plus'), ('Iphone 7 ', 'Iphone 7'), ('Iphone 6S Plus', 'Iphone 6S Plus'), ('Iphone 6s', 'Iphone 6s'), ('Iphone 6', 'Iphone 6'), ('Iphone SE 2nd Gen', 'Iphone SE 2nd Gen'), ('Iphone SE', 'Iphone SE')], default=0, max_length=30)),
                ('carrier', models.CharField(choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30)),
                ('capacity', models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30)),
                ('condition', models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=30, null=True)),
                ('Offer', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ipod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipod_model', models.CharField(choices=[('Touch', 'Touch')], default=0, max_length=30)),
                ('ipod_capacity', models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=0, max_length=30)),
                ('ipod_generation', models.CharField(choices=[('1st Gen', '1st Gen'), ('2nd Gen', '2nd Gen'), ('3rd Gen', '3rd Gen'), ('4th Gen', '4th Gen'), ('5th Gen', '5th Gen'), ('6th Gen', '6th Gen'), ('7th Gen', '7th Gen')], default=0, max_length=30)),
                ('ipod_condition', models.CharField(choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30)),
                ('ipod_engraving', models.CharField(choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30)),
                ('offer', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Iwatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iwatch_model', models.CharField(choices=[('Apple Watch Original(1st Gen)', 'Apple Watch Original(1st Gen)'), ('Apple Watch Series 1', 'Apple Watch Series 1'), ('Apple Watch Series 2', 'Apple Watch Series 2'), ('Apple Watch Series 3', 'Apple Watch Series 3'), ('Apple Watch Series 4', 'Apple Watch Series 4'), ('Apple Watch Series 5', 'Apple Watch Series 5')], default=0, max_length=30)),
                ('iwatch_carrier', models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=0, max_length=30, null=True)),
                ('iwatch_edition_casing', models.CharField(blank=True, choices=[('Aluminium Case', 'Aluminium Case'), ('Regular-Steel Case', 'Regular-Steel Case'), ('Hermes-Steel Case', 'Hermes-Steel Case'), ('Stainless-Steel Case', 'Stainless-Steel Case'), ('Titanium Case', 'Titanium Case'), ('Ceramic Case', 'Ceramic Case'), ('Nike+ -Aluminium Case', 'Nike+ -Aluminium Case')], default=0, max_length=30, null=True)),
                ('iwatch_size', models.CharField(blank=True, choices=[('38mm', '38mm'), ('40mm', '40mm'), ('42mm', '42mm'), ('44mm', '44mm')], default=0, max_length=30, null=True)),
                ('iwatch_band', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Sport Band-Any Color', 'Sport Band-Any Color'), ('Sport Loop-Any Color', 'Sport Loop-Any Color'), ('Nylon Band-Any Color', 'Nylon Band-Any Color'), ('Milanese Loop', 'Milanese loop'), ('Classic Buckle', 'Classic Buckle'), ('Leather Loop', 'Leather Loop'), ('Modern Buckle', 'Modern Buckle'), ('Hermes Band', 'Hermes Band'), ('Link Bracelet', 'Link Bracelet'), ('Gold Buckle-Any Band', 'Gold Buckle-Any Band'), ('No Band', 'No Band')], default=0, max_length=30, null=True)),
                ('iwatch_condition', models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30, null=True)),
                ('iwatch_functional', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('iwatch_powercord', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('iwatch_box', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('offer', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Macbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macbook_model', models.CharField(choices=[('Macbook', 'Macbook'), ('Macbook Air', 'Macbook Air'), ('Macbook Pro', 'Macbook Pro')], default=0, max_length=30)),
                ('screen_size', models.CharField(blank=True, choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], default=None, max_length=30, null=True)),
                ('year', models.CharField(blank=True, choices=[('Mid 2012', 'Mid 2012'), ('Late 2012', 'Late 2012'), ('Early 2013', 'Early 2013'), ('Mid 2013', 'Mid 2013'), ('Late 2013', 'Late 2013'), ('Early 2014', 'Early 2014'), ('Mid 2014', 'Mid 2014'), ('Early 2015', 'Early 2015'), ('Mid 2015', 'Mid 2015'), ('Early 2016', 'Early 2016'), ('Late 2016', 'Late 2016'), ('2016', '2016'), ('2017', '2017'), ('Mid 2017', 'Mid 2017'), ('Mid 2018', 'Mid 2018'), ('Late 2018', 'Late 2018'), ('2019', '2019'), ('Mid 2019', 'Mid 2019'), ('2018', '2018'), ('2020', '2020')], default=None, max_length=30, null=True)),
                ('touch', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('processer', models.CharField(blank=True, choices=[('Core 2 Duo', 'Core 2 Duo'), ('1.1Ghz', '1.1Ghz'), ('M 1.1Ghz', 'M 1.1Ghz'), ('M 1.2Ghz', 'M 1.2Ghz'), ('M 1.3Ghz', 'M 1.3Ghz'), ('m3 1.1Ghz', 'm3 1.1Ghz'), ('m5 1.2Ghz', 'm5 1.2Ghz'), ('m7 1.3Ghz', 'm7 1.3Ghz'), ('m3 1.2Ghz', 'm3 1.2Ghz'), ('i5 1.3Ghz ', 'i5 1.3Ghz'), ('i7 1.4Ghz', 'i7 1.4Ghz'), ('i5', 'i5'), ('i7', 'i7'), ('1.2Ghz', '1.2Ghz'), ('1.3 i5 Ghz', '1.3 i5Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.3Ghz', '1.3Ghz'), ('1.4Ghz', '1.4Ghz'), ('1.6Ghz', '1.6Ghz'), ('1.7Ghz', '1.7Ghz'), ('1.8Ghz', '1.8Ghz'), ('2.0Ghz', '2.0Ghz'), ('2.2Ghz', '2.2Ghz'), ('2.3Ghz', '2.3Ghz'), ('2.30Ghz', '2.30Ghz'), ('2.4Ghz', '2.4Ghz'), ('2.5Ghz', '2.5Ghz'), ('2.6Ghz', '2.6Ghz'), ('2.60Ghz', '2.60Ghz'), ('2.7Ghz', '2.7Ghz'), ('2.8Ghz', '2.8Ghz'), ('2.9Ghz', '2.9Ghz'), ('3.0Ghz', '3.0Ghz'), ('3.1Ghz', '3.1Ghz'), ('3.3Ghz', '3.3Ghz'), ('3.5Ghz', '3.5Ghz')], default=None, max_length=30, null=True)),
                ('cosmetic_condition', models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30, null=True)),
                ('ram_capacity', models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True)),
                ('storage_capacity', models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True)),
                ('battery_health', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Broken', 'Broken'), ('Fair', 'Fair'), ('Good', 'Good'), ('Flawless', 'Flawless')], default=None, max_length=30, null=True)),
                ('macbook_functional', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('macbook_powercord', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('graphics_card', models.CharField(blank=True, choices=[('1.1Ghz i3', '1.1Ghz i3'), ('1.1Ghz i5', '1.1Ghz i5'), ('Dedicated Graphics', 'Dedicated Graphics'), ('Retina', 'Retina'), ('No Retina', 'No Retina'), ('Touch Vega', 'Touch Vega'), ('Touch', 'Touch'), ('AMD Radeon R9 M370X Graphics', 'AMD Radeon R9 M370X Graphics'), ('Nvidia Geforce GT 750 Graphics', 'Nvidia Geforce GT 750 Graphics'), ('AMD Radeon Pro 555X', 'AMD Radeon Pro 555X'), ('AMD Radeon Pro 560X', 'AMD Radeon Pro 560X'), ('AMD Radeon Pro Vega 16', 'AMD Radeon Pro Vega 16'), ('AMD Radeon Pro Vega 20', 'AMD Radeon Pro Vega 20'), ('AMD Radeon Pro 5300M w/4GB', 'AMD Radeon Pro 5300M w/4GB'), ('AMD Radeon Pro 5500M w/4GB', 'AMD Radeon Pro 5500M w/4GB'), ('AMD Radeon Pro 5500M w/8GB', 'AMD Radeon Pro 5500M w/8GB'), ('AMD Radeon Pro 5600M w/8GB HBM2', 'AMD Radeon Pro 5600M w/8GB HBM2')], default=0, max_length=30, null=True)),
                ('offer', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SamsungPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samsung_model', models.CharField(choices=[('Galaxy Fold', 'Galaxy Fold'), ('Galaxy Z-Flip', 'Galaxy Z-Flip'), ('Galaxy Fold SM-F900', 'Galaxy Fold SM-F900'), ('Galaxy Note 10+ 5G', 'Galaxy Note 10+ 5G'), ('Galaxy Note 10+', 'Galaxy Note 10+'), ('Galaxy Note 10', 'Galaxy Note 10'), ('Galaxy Note 9', 'Galaxy Note 9'), ('Galaxy Note 8', 'Galaxy Note 8'), ('Galaxy S10+', 'Galaxy S10+'), ('Galaxy S10', 'Galaxy S10'), ('Galaxy S10 5G', 'Galaxy S10 5G'), ('Galaxy S10 Lite', 'Galaxy S10 Lite'), ('Galaxy S10e', 'Galaxy S10e'), ('Galaxy S9+', 'Galaxy S9+'), ('Galaxy S9', 'Galaxy S9'), ('Galaxy S8+', 'Galaxy S8+'), ('Galaxy S8 Active', 'Galaxy S8 Active'), ('Galaxy S8', 'Galaxy S8'), ('Galaxy S7 Edge', 'Galaxy S7 Edge'), ('Galaxy S7', 'Galaxy S7'), ('Galaxy S6 Edge+', 'Galaxy S6 Edge+'), ('Galaxy S6 Edge', 'Galaxy S6 Edge'), ('Galaxy S6', 'Galaxy S6'), ('Galaxy S20 5G', 'Galaxy S20 5G'), ('Galaxy S20 Ultra 5G', 'Galaxy S20 Ultra 5G'), ('Galaxy S20+ 5G', 'Galaxy S20+ 5G')], default=0, max_length=30)),
                ('samsung_capacity', models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('64 GB SSD', '64 GB SSD'), ('80 GB', '80 GB'), ('120 GB ', '12O GB '), ('128 GB SSD', '128GB SSD'), ('128 GB ', '128 GB '), ('256 GB', '256 GB'), ('256 GB SSD', '256 GB SSD'), ('512 GB', '512 GB'), ('512 GB SSD', '512 GB SSD'), ('750 GB', '750 GB'), ('1 TB', '1 TB'), ('1.5 TB', '1.5 TB'), ('1 TB SSD', '1 TB SSD'), ('2 TB SSD', '2 TB SSD'), ('3 TB SSD', '3 TB SSD'), ('4 TB SSD', '4 TB SSD'), ('not known', "Don't Know")], default=None, max_length=30, null=True)),
                ('samsung_carrier', models.CharField(blank=True, choices=[('att', 'AT&T'), ('verizon', 'Verizon'), ('tmobile', 'Tmobile'), ('sprint', 'Sprint'), ('unlocked', 'Factory Unlocked'), ('other', 'Other'), ('not known', "Don't Know"), ('wifi', 'Wifi'), ('wifi Only', 'Wifi Only'), ('GPS', 'GPS'), ('GPS + Cellular', 'GPS + Cellular'), ('U.S Cellular', 'U.S Cellular'), ('Xfinity', 'Xfinity'), ('Cricket', 'Cricket')], default=None, max_length=30, null=True)),
                ('samsung_isunlock', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('samsung_condition', models.CharField(blank=True, choices=[('Broken', 'Broken'), ('Working%', 'Working'), ('30%', '30%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=None, max_length=30, null=True)),
                ('samsung_functional', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('samsung_screenburn', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('samsung_powercord', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('samsung_box', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('samsung_headset', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No%', 'no')], default=None, max_length=30, null=True)),
                ('offer', models.CharField(default=0, max_length=4)),
            ],
        ),
    ]
