# Generated by Django 2.2.10 on 2022-08-04 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInquery',
            fields=[
                ('caseNo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=30, null=True)),
                ('topic', models.CharField(choices=[('Payment Status', 'Payment Status'), ('My Order', 'My Order'), ('Returns', 'Returns'), ('Cancellation', 'Cancellation'), ('Shipping Status', 'Shipping Status'), ('General Information', 'General Information'), ('Other', 'Other')], max_length=30, null=True)),
                ('subject', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquerer',
            fields=[
                ('inqueryNo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('companyOrganization', models.CharField(max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=30, null=True)),
                ('additionalInfo', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceOrder', models.IntegerField(blank=True, null=True)),
                ('deviceType', models.CharField(max_length=30, null=True)),
                ('deviceCondition', models.CharField(max_length=30, null=True)),
                ('deviceQuantity', models.IntegerField(blank=True, null=True)),
                ('inquerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sellbulk.Inquerer')),
            ],
        ),
    ]
